version: '3.8'

services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 & 
               celery -A app.api.prediction.services.prediction_service.app worker --loglevel=info --pool=solo &
               celery -A app.api.prediction.services.prediction_service.app flower --port=5555"
    depends_on:
      - redis

  
